#!/usr/bin/env bash

sudo apt update 
git clone https://github.com/maurosoria/dirsearch.git
git clone https://github.com/danielmiessler/SecLists.git
sudo apt install curl amass masscan nmap ffuf cewl
