#!/usr/bin/env bash
echo "INTEGRACION DE REPOSITORIO DE KALI LINUX:"
sudo apt update 
sudo apt upgrade
sudo sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
sudo apt install gnupg
wget 'https://archive.kali.org/archive-key.asc'
sudo apt-key add archive-key.asc
sudo sh -c "echo 'Package: *'>/etc/apt/preferences.d/kali.pref; echo 'Pin: release a=kali-rolling'>>/etc/apt/preferences.d/kali.pref; echo 'Pin-Priority: 50'>>/etc/apt/preferences.d/kali.pref"
sudo apt update
echo "INTEGRACION DE REPOSITORIOS EXITOSA"
sudo apt update 
git clone https://github.com/maurosoria/dirsearch.git
git clone https://github.com/danielmiessler/SecLists.git
sudo apt install curl amass masscan nmap ffuf cewl
