#!/usr/bin/env bash

cd ~
sudo apt install firefox-esr
sudo apt install wget
git clone https://github.com/FortyNorthSecurity/EyeWitness.git
cd boxsetup
sudo mv geckodriver /usr/sbin
cd ..
cd EyeWitness
cd Python/setup
sudo ./setup.sh
cd ~

