#!/usr/bin/env bash

cd ~
sudo apt install firefox-esr
git clone https://github.com/FortyNorthSecurity/EyeWitness.git
cd boxsetup
sudo mv geckodriver /usr/sbin
cd ..
cd EyeWitness
cd Python/setup
sudo ./setup.sh
cd ~
wget https://docs.google.com/uc?id=0B3X9GlR6EmbnWksyTEtCM0VfaFE&export=download
mv uc\?id\=0B3X9GlR6EmbnWksyTEtCM0VfaFE gdrive
chmod +x gdrive
sudo install gdrive /usr/local/bin/gdrive
gdrive list
