#!/usr/bin/env bash

sudo apt update
sudo apt upgrade 
curl -O https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz
sudo tar -xvf go1.15.6.linux-amd64.tar.gz -C /usr/local
sudo chown -R root:root /usr/local/go
mkdir -p $HOME/go/{bin,src}
paste goVariables.txt >> ~/.profile

echo " "
source ~/.profile
. ~/.profile
echo " "
go get -u github.com/tomnomnom/assetfinder
go get -u github.com/tomnomnom/httprobe
go get github.com/tomnomnom/waybackurls
go get -u github.com/tomnomnom/meg
go get github.com/hakluke/hakrawler
go get -u github.com/jaeles-project/gospider
GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder



echo "#############################################################################################################"
echo "INTEGRACION DE REPOSITORIO DE KALI LINUX:"
sudo apt update
sudo apt upgrade
sudo sh -c "echo 'deb https://http.kali.org/kali kali-rolling main non-free contrib' > /etc/apt/sources.list.d/kali.list"
sudo apt install gnupg
wget 'https://archive.kali.org/archive-key.asc'
sudo apt-key add archive-key.asc
sudo sh -c "echo 'Package: *'>/etc/apt/preferences.d/kali.pref; echo 'Pin: release a=kali-rolling'>>/etc/apt/preferences.d/kali.pref; echo 'Pin-Priority: 50'>>/etc/apt/preferences.d/kali.pref"
sudo apt update
echo " "
sudo apt-get update 
sudo apt install sublist3r amass masscan nmap python

sudo apt install python3-pip
sudo apt install python-pip
rm go1.15.6.linux-amd64.tar.gz

git clone https://github.com/gwen001/github-search.git
cd github-search
pip3 install -r requirements2.txt
pip3 install -r requirements3.txt 
cd ~
pip install py-altdns
git clone https://github.com/danielmiessler/SecLists.git
