#!/usr/bin/env bash

apt update
apt install curl
curl -O https://dl.google.com/go/go1.15.6.linux-amd64.tar.gz
tar -xvf go1.15.6.linux-amd64.tar.gz -C /usr/local
chown -R root:root /usr/local/go
mkdir -p $HOME/go/{bin,src}
paste goVariables.txt >> ~/.profile

echo " "
source ~/.profile
. ~/.profile
echo " "
go get -u github.com/tomnomnom/assetfinder
go get -u github.com/tomnomnom/httprobe
go get github.com/tomnomnom/waybackurls
go get -u github.com/tomnomnom/meg
go get github.com/hakluke/hakrawler
go get -u github.com/jaeles-project/gospider
GO111MODULE=on go get -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder

apt install sublist3r amass masscan nmap python

apt install python3-pip
apt install python-pip
rm go1.15.6.linux-amd64.tar.gz

git clone https://github.com/gwen001/github-search.git
cd github-search
pip3 install -r requirements2.txt
pip3 install -r requirements3.txt 
cd ~
pip install py-altdns
git clone https://github.com/danielmiessler/SecLists.git
